blogger/urls.py
from django.contrib import admin
from django.urls import path,include
from users import urls
from  . import views
from django.conf.urls.static import static
from django.conf import settings
from drafts import urls
from moderator import urls
from users import urls
from writer import urls
from admins import urls
urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'users/', include('users.urls')),
    path(r'', views.red),
    path(r'drafts/', include('drafts.urls')),
    path(r'moderator/', include('moderator.urls')),
    path(r'writer/', include('writer.urls')),
    path(r'admins/', include('admins.urls'))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

drafts/urls.py
from django.contrib import admin
from django.urls import path,include
from users import urls
from  . import views
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url

app_name = 'drafts'
urlpatterns = [
    path(r'articledisp/', views.articledisp),
    #path(r'articleview/< id >/', views.articleview)
    url(r'^(?P<slug>[\w-]+)/$',views.articleview,name="details"),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

users/urls.py
from django.contrib import admin
from django.urls import path
from  . import views


urlpatterns = [
    path('login/', views.login1),
    path('signup/', views.signup),
    path('logout/',views.logout1),
    path('addmoderator/',views.addmoderator),
]

drafts/models.py
from django.db import models

# Create your models here.
class drafts(models.Model):
    #doc_id = models.CharField(max_length = 20, primary_key = True)
    title = models.CharField(max_length = 100)
    body = models.TextField()
    date_of_update = models.DateField()
    date_of_publish = models.DateField()
    status = models.IntegerField()
    thumbnail = models.ImageField(upload_to = 'thumbs')
    author = models.CharField(max_length = 20)
    slug = models.SlugField()


    def __str__(self):
        return ' '.join(list([self.title, self.slug, str(self.date_of_update), str(self.date_of_publish)]))

    def snippet(self):
        return self.body[:120] + '...'

drafts/views.py
from django.shortcuts import render
from .models import drafts
# Create your views here.

def articledisp(request):
    draft = drafts.objects.filter(status = 4)

    return render(request, 'drafts/articledisp.html', {
        'docs' : draft
     })
    
def articleview(request,slug):
    d = drafts.objects.get(slug = slug)
    bodylist = list(d.body.split('\n'))
    return render(request,'drafts/articleview.html',{'doc' : d , 'body1' : bodylist})

drafts/templates/drafts/articledisp.html
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <meta name="viewport" content="width=device-width, initial-scale=1.0">#}
{#    <meta http-equiv="X-UA-Compatible" content="ie=edge">#}
{#    <title>Document</title>#}
{#</head>#}
{#<body>#}
{#    <a href="/users/signup/"><input type="button" value="Sign-up"></a>#}
{#    <a href="/users/login/"><input type="button" value="Login"></a>#}
{#    <div>#}
{#        {% for doc in docs %}#}
{#        <center>#}
{#            <img src="{{ doc.thumbnail.url }}" alt=""  width="640px" height="480px">#}
{#            <br>#}
{#            <a href = "{% url 'drafts:details' slug=doc.slug %}" ><h1>{{ doc.title }}</h1></a>#}
{#            <br>#}
{#        </center>#}
{#        {% endfor %}#}
{#    </div>#}
{#</body>#}
{#</html>#}

{% load static from staticfiles %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>SPark</title>

        <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Lora'>
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <link rel="icon" href="{% static 'logo.PNG' %}">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

        <style>

            .background-wrap {
                position: fixed;
                z-index: -1000;
                width: 100%;
                height: 100%;
                overflow: hidden;
                top: 0;
                left: 0;
            }

            video {
                position: absolute;
                top: 0;
                left: 0;
                min-height: 100%;
                min-width: 100%;
            }

        </style>
    </head>

    <body style="margin: 60px;font-family: Lora;background-color: #eecbb5">
    <div class="background-wrap">
        <video preload="auto" autoplay loop="loop" muted="muted">
            <source src="{% static 'video.mp4' %}" type="video/mp4">
            Video not supported
        </video>
    </div>
        <div class="row" style="text-align: center;background-color: rgba(255,255,255,0.62)">
            <br>
            <h4 style="color: #24a89c">
                SPark, the official newsletter for S.P.I.T.
                <i class="material-icons" style="font-size: 30px;vertical-align:middle !important;">whatshot</i>
            </h4>
            <br>
        </div>

        <div class="row">
            {% for doc in docs %}
            <!-------------------BLOG----------------->
            <div class="col s12 m4 cards-container">
                <div class="card">
                    <div class="card-image">
                        <img src="{{ doc.thumbnail.url }}">
                        <a href="{% url 'drafts:details' slug=doc.slug %}" target="_blank" class="btn-floating btn-large halfway-fab waves-effect waves-light teal">
                            <i class="material-icons">launch</i>
                        </a>
                    </div>
                    <div class="card-content">
                        <br>
                        <span class="card-title center-align teal-text">{{ doc.title }}</span>
                        <p style="text-align: justify">
                            {{ doc.snippet }}
                        </p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </body>
</html>

drafts/templates/drafts/articleview.html
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <meta name="viewport" content="width=device-width, initial-scale=1.0">#}
{#    <meta http-equiv="X-UA-Compatible" content="ie=edge">#}
{#    <title>{{ doc.title }}</title>#}
{#</head>#}
{#<body>#}
{##}
{#    <div>#}
{#        <center>#}
{#            <h1>{{ doc.title }}</h1>#}
{#            <img src="{{ doc.thumbnail.url }}" alt="" width="640px" height="480px">#}
{##}
{#            <p>#}
{#                {% for i in body1 %}#}
{#                {{ i }}<br>#}
{#                {% endfor %}#}
{#            </p>#}
{#        </center>#}
{#    </div>#}
{#    #}
{#</body>#}
{#</html>#}

{% load static from staticfiles  %}

<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
{#        <title>{{ doc.title }}</title>#}
        <title>SPark</title>
        <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Lora'>
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <link rel="icon" href="{% static 'logo.PNG' %}">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    </head>


    <body style="font-family: Lora,serif;">


        <div class="parallax-container" style="height: 250px;">
            <div class="parallax">
                <img src="{% static 'blogbg.jpg' %}" alt="" class="responsive-img" >
            </div>
        </div>

        <h1 style="text-align: center">{{ doc.title }}</h1>
        <div style="text-align: center">
            <img src="{{ doc.thumbnail.url }}" style="height: 300px">
        </div>
        <p style="text-align: justify;margin: 50px 200px">
            {% for i in body1 %}
                {{ i }}<br>
            {% endfor %}
        </p>

  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>
        <script>
            $(document).ready(function(){
                $('.parallax').parallax();
            });
        </script>
    </body>
</html>